# Generated by Django 4.2.13 on 2024-06-06 16:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('username', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z0-9_]+$')])),
                ('email', models.EmailField(max_length=255, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('password', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('username', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z0-9_]+$')])),
                ('full_name', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z ]+$')])),
                ('email', models.EmailField(max_length=255, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('password', models.CharField(max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(8)])),
                ('phone_number', models.IntegerField(unique=True, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'Phone number must be 11 digits', 'Invalid number')])),
            ],
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.RenameField(
            model_name='orders_product',
            old_name='order_id',
            new_name='orders_order_id',
        ),
        migrations.AlterField(
            model_name='orders',
            name='type',
            field=models.BinaryField(),
        ),
        migrations.RenameModel(
            old_name='User_Orders',
            new_name='Users_Orders',
        ),
        migrations.AlterField(
            model_name='orders',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.users'),
        ),
        migrations.AlterField(
            model_name='users_orders',
            name='users_username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.users'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
